management:
    otlp:
      metrics.export.enabled: true
      metrics.export.step: 5s
      tracing.export.enabled: true
    metrics.tags.application: ${spring.application.name}
    tracing.sampling.probability: 1.0

spring:
  ai:
    chat.observations.include-error-logging: true
    tools.observations.include-content: true
  docker.compose:
    enabled: true
    profiles.active: observability