spring:
  application.name: nutrition-planner
  profiles.active: openai
  security.user:
      password: 123456
      name: alice
  ai:
    # Define AI provider(s) for type of models for autoconfiguration
    model:
      chat: none
      embedding: none
      image: none
      audio:
        speech: none
        transcription: none
      moderation: none
    tools.observations.include-content: true
    mcp.server:
      name: ${spring.application.name}
      protocol: STREAMABLE

management:
  endpoints.web.exposure.include: "*"
  otlp.metrics.export.enabled: false

logging.level:
  org.springaicommunity: debug
  org.springframework.ai: debug

nutrition-planner:
  user-profiles:
    - name: alice
      dietary-restrictions:
        - vegetarian
      health-goals:
        - weight-loss
        - improve-energy
      daily-calorie-target: 1800
      allergies:
        - nuts
      disliked-ingredients:
        - cilantro
        - olives
