spring:
  ai:
    # Define AI provider(s) for type of models for autoconfiguration
    model:
      chat: openai
      embedding: openai
    # AI provider configuration
    openai:
      chat.model: ${AZURE_OPENAI_DEPLOYMENT_NAME}
      endpoint: ${AZURE_OPENAI_ENDPOINT}
      api-key: ${AZURE_OPENAI_API_KEY}